Build entity User and Authoriry (Base Entity) #11
Semerkosa/3vial pull request #12
Opened 2021-09-22 16:48 UTC by stspot

2021-09-22 17:50 UTC, Semerkosa requested changes
@ManyToOne
User --> Address

Ако в едно домакинство двама искат да използват сайта, какво правим? :) 

И като скромен коментар..Излишна е Column анотацията за default naming.

2021-09-23 11:53 UTC, smanilov commented
@stspot : Моля провери конкретиките за one-to-one, many-to-one и т.н. и да обобщиш тук.

2021-09-24 08:11 UTC, Semerkosa commented on server/src/main/java/io/trivial/entity/Address.java
> +
Смятам, че е логично да можем да търсим потребителите по адреси, т.е. ни трябва още едно поле - "private Set<User> users" с връзка към User таблицата OneToMany.

2021-09-24 08:14 UTC, Semerkosa commented on server/src/main/java/io/trivial/entity/User.java
> +	@OneToOne
Тук мисля, че ще е по-добре връзката с таблицата с адреси да е ManyToOne, за да няма дублиране на адреси.

2021-09-25 17:02 UTC, ANeshkova commented on server/src/main/java/io/trivial/entity/Address.java
> +
Според теб в каква ситуация би ни било необходимо да търсим потребителите по адреси? Например, за да събираме някакви статистически данни или?

2021-09-25 20:49 UTC, Semerkosa commented on server/src/main/java/io/trivial/entity/Address.java
> +
Точно така! За някакъв вид статистика или сортировка. Ще е по-лесно с bidirectional връзка, отколкото с някакъв join в самата база. Например, каква част от потребителите живеят на един адрес(set.size > 1).

2021-09-28 08:28 UTC, GGerginov approved these changes

2021-09-28 12:28 UTC, closed without merging